config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :users
  resources :posts

  get '/login' => 'sessions#new', as: :login
  post "/login" => 'sessions#create'
  delete "/logout" => 'sessions#destroy', as: :logout
  get 'posts/:id/share' => 'posts#share', as: :share
  post 'posts/:id/share' => 'posts#email'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  mount_uploader :photo_upload, PhotoUploader

  validates :body, :title, :user, presence: true

  def is_owner?(this_user)
    user == this_user
  end

end

app/models/user.rb
class User < ApplicationRecord

has_secure_password

has_many :posts

validates :username, presence: true, uniqueness:true
validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :get_posts

  helper_method :current_user

  private

  def get_posts
    @posts = Post.all.order(created_at: :desc).first(4)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :find_post, only: [:edit, :show, :update]

  def index
    @post = Post.all.order(created_at: :desc).first
    @posts = Post.all.order(created_at: :desc).offset(1).first(4)
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.all.order(created_at: :desc).where("id != ?", @post.id).first(4)
    render :index
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def share
    @post = Post.find(params[:id])
    @user = current_user
    render 'sharepostform'
  end

  def email
    @post = Post.find(params[:id])
    @user = current_user
    flash[:success] = "The post was successfully shared!"
     SharePostMailer.share(@post, @user, params[:share][:email]).deliver
     redirect_to @post
  end

  private

  def post_params
    params.require(:post).permit(:user_id,:title, :body, :photo, :photo_upload)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Trikke and Turf, #{@user.username}!"
      redirect_to :root
    else
      flash[:danger] = "Login invalid. Please check credentials and try again."
      redirect_to :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup(@user).deliver
      session[:user_id] = @user.id
      redirect_to :root
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :bio, :email, :image, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def require_owner
    unless @user == current_user
      redirect_to :root
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trikke_helper.rb
module TrikkeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Trikke and Turf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css" />
  </head>

    <body>
      <header>
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-logo">
              <!-- Navbar goes here -->
              <%= link_to root_path do%>
              <%= image_tag "tata_logo.svg", alt:"TaTa Logo"%>
              <% end %>
              <span class="text-uppercase">Trikke &amp; Turf Association</span>
            </div>
            <div class="col-sm-6 col-nav text-right">
            <% unless current_user %>
              <%= link_to "Login", login_path, class: "text-uppercase" %>
              <%= link_to "Sign-up", new_user_path, class: "text-uppercase" %>
            <% end %>

             <% if current_user %>
              <%= link_to "New Post", new_post_path %>
              <%= link_to "Logout,  #{current_user.username}", logout_path, method: "delete" %>
             <% end %>
             <a href="" class="text-uppercase">About</a>
             <a href="" class="text-uppercase">Search <i class="glyphicon glyphicon-search"></i></a>
             <!-- End Navbar  -->
           </div>
            <div class="row">
              <div class="col-sm-12 col-brand text-center">
                <h1 class="text-uppercase">Trikke &amp; Turf Assoc.</h1>
                <span>An Iron Yard Academy Project Est. Spring 2017</span>
              </div>
            </div>
          </div>
        </div>
      </header>

    <div class="container-fluid">
    <!--Container for Bootstrap elements -->
      <%= yield %>
    </div>
    <hr />
    <div class ="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <h1 class="text-uppercase text-center pop-posts">Most Popular Posts</h1>
        </div>
      </div>

      <div class="row">
        <% @posts.each.with_index do |post, i| %>
          <div style="background-image: linear-gradient(rgba(15,109,181,0.3), rgba(15,109,181,0.75)), url(<%= image_path post.photo == "" ? post.photo_upload : post.photo %>);" id="post<%= i + 1 %>" class="col-sm-3 photos text-center">
          <h3><%= link_to post.title, post, class:"bottom" %></h3>
        </div>
       <% end %>
      </div>
    </div>

    <footer>
      <div class="row container-fluid">
        <div class="col-sm-offset-1 col-sm-5 text-center">
          <%= image_tag "ironyardlogo.png", class: "logo", alt:"The Iron Yard Logo" %>
          <span>The Ironyard Copyright 2013, All Rights Reserved</span>
        </div>

        <div class="col-sm-offset-2 col-sm-4 ft-nav-items text-right">
          <a class="ft-nav-items" href="#"> &nbsp; Nav Item 1 &nbsp; </a> |
          <a class="ft-nav-items" href="#"> &nbsp; Nav Item 2 &nbsp; </a> |
          <a class="ft-nav-items" href="#"> &nbsp; Nav Item 3 &nbsp; </a> |
          <a class="ft-nav-items"href="#"> &nbsp; Nav Item 4 &nbsp; </a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<div class="row">
  <div class="bg-danger col-sm-3 text-center col-sm-offset-2">
    <ul class="list-unstyled">
      <% @post.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
    <%= simple_form_for @post, html: {class: "form-horizontal"} do |f| %>
      <%= f.input :photo%>
      <%= f.input :photo_upload %>
      <%= f.input :title %>
      <%= f.input :body %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="text-center">Edit a blog post!</h1>

<%= render "/posts/form" %>

app/views/posts/index.html.erb
<div class="row">

    <!--Post Title goes here-->
    <div class="col-sm-5 col-sm-offset-1 blog">
      <h1 class="title text-uppercase"><%= @post.title%></h1>
        <!-- Avatar goes here -->
        <%= image_tag @post.user.image, class: "img-circle author-small", alt: "#{@post.user.username}'s avatar" %>

        <!-- Username goes here -->
        <%= @post.user.username.capitalize %>

        <!-- Timestamp goes here -->
        on <%= link_to @post.created_at.strftime("%A %b. %e %l:%m%P") %>

        <!-- Post body goes here -->
          <%= simple_format @post.body, class:"blog-body" %>
          <% if @post.photo_upload != nil %>
          <%= image_tag @post.photo_upload %>
          <% end %>
          <br /><br />

          <a href="#" class="primary">
          <span class="button-icon">
          <i class="glyphicon glyphicon-comment"></i>
          </span>
          <span class="button-label">Read Comments</span>
        </a>
        <a href="#" class="primary">
          <span class="button-icon">
            <i class="glyphicon glyphicon-cloud-upload"></i>
          </span>
          <span class="button-label">Read Later</span>
        </a>
        <%= link_to share_path(@post), class:"primary" do %>
          <span class="button-icon">
          <i class="glyphicon glyphicon-plus"></i>
          </span>
          <span class="button-label">Share This Post</span>
        <% end %>
    </div>

    <div class="col-sm-5 col-sm-offset-1 items-center about">
      <%= image_tag @post.user.image, class: "img-circle author-large", alt: "#{@post.user.username}'s avatar" %>
      <%= simple_format @post.user.username.capitalize, class: "text-center" %>
      <div class="social_links text-center">
        <a href="http://www.twitter.com"> Twitter</a>
        <a href="http://www.facebook.com">Facebook</a>
        <a href="http://www.instagram.com">Instagram</a>
        <br />
        <% if flash[:success] %>
          <%= simple_format flash[:success], class:"alert alert-success" %>
        <% end %>
        <br />
        <% if current_user %>
          <!-- Show New Post Button -->
          <%= link_to new_post_path, class:"primary" do %>
            <span class="button-icon">
            <i class="glyphicon glyphicon-plus"></i>
            </span>
            <span class="button-label">New Post</span>
          <% end %>
          <!-- Show Edit Post Button  -->
          <% if current_user == @post.user %>
            <%= link_to edit_post_path(@post), class:"primary" do %>
              <span class="button-icon">
              <i class="glyphicon glyphicon-pencil"></i>
              </span>
              <span class="button-label">Edit Post</span>
            <% end %>
          <% end %>
          <!-- Show Sign Out Button -->
          <%= link_to logout_path, class:"primary", method: "delete" do %>
            <span class="button-icon">
            <i class="glyphicon glyphicon-plus"></i>
            </span>
            <span class="button-label">Logout</span>
          <% end %>
        <% end %>
      </div>

      <div class="ads">
        <%= image_tag "redtrikke.jpg", class: "fake-ad-image items-center" %>
        <p class="col-sm-5 col-sm-offset-4 text-right"><a href="#">About this ad</a></p><br />
      </div>
      <div class="col-sm-5 col-sm-offset-3 author-bio">
        <h5 class="text-center text-uppercase">About <%=@post.user.username %></h5>
        <%= simple_format @post.user.bio, class: "text-left" %>
      </div>
    </div>

<!--End Center Content Row-->
</div>

app/views/posts/new.html.erb
<h1 class="text-center">Create a new blog post!</h1>

<%= render "/posts/form" %>

app/views/posts/sharepostform.html.erb
<%= simple_format @post.user.username %>
<%= simple_format  @post.title %>
<% simple_format @post.body %>

<div class = "container">
  <div class="row">
    <div class="col-sm-6">
      <%= simple_form_for :share do |f| %>
        <%= f.input :user %>
        <%= f.input :email %>
        <%= f.submit "Share", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!-- Uses index.html.erb for rendering content -->
<!-- See also PostsController for action information and variables available -->

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div class="row">
  <div class="bg-danger col-sm-3 text-center col-sm-offset-2">
    <ul class="list-unstyled">
      <!-- <% @user.errors.full_messages.each do |message| %> -->
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<h1>Sign-up:</h1>
<%= simple_form_for @user do |f| %>
<%= f.input :username %>
<%= f.input :password %>
<%= f.input :email %>
<%= f.input :image %>
<%= f.input :bio %>
<%= f.button :submit, "Create", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>